name: Generate Resume Preview on PR
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    paths:
      - "resume.md"
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:
jobs:
  generate-resume:
    name: Generate Resume
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build resume output
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: resume.md
          output_dir: resume
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: resume

  deploy-pr-preview:
    name: Deploy PR Preview
    runs-on: ubuntu-latest
    needs: generate-resume
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Artifacts
        if: github.event.action != 'closed'
        uses: actions/download-artifact@v4
        with:
          name: Resume
          path: resume
      - name: Make pages directory
        if: github.event.action != 'closed'
        run: mkdir pages
      - name: Copy HTML for pages preview
        if: github.event.action != 'closed'
        run: cp resume/resume.html pages/index.html
      - name: Deploy HTML Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: pages
          umbrella-dir: pr-preview
          action: auto
