name: Release Resume
on:
  push:
    branches:
      - main
    paths:
      - "resume.md"
    tags:
      - "*"

jobs:
  generate-resume:
    name: Generate Resume Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build resume output
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: resume.md
          output_dir: out
      - name: Rename pdf resume
        run: cp out/resume.pdf mikeodriscoll_resume.pdf
      - name: Rename html resume
        run: cp out/resume.html index.html
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: mikeodriscoll_resume.pdf
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HTML
          path: index.html

  release-pdf-resume:
    name: Release Resume
    permissions:
      contents: write # Required for Upload release assets
    needs: generate-resume
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: PDF
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: mikeodriscoll_resume.pdf

  publish-github-pages:
    name: Update Github Pages
    needs: generate-resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: HTML
          path: release
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release
          branch: gh-pages
          clean-exclude: pr-preview
