name: Release Resume
on:
  push:
    tags:
      - "*"

jobs:
  generate-resume:
    permissions:
      contents: write # Required for Upload release assets
    name: Release Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build resume output
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_path: resume.md
          output_dir: out
      - name: Rename pdf resume
        run: mv out/resume.pdf mikeodriscoll_resume.pdf
      - name: Rename html resume
        run: mv out/resume.html out/index.html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HTML Release
          path: out/index.html
          retention-days: 5
      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            out/resume.html
            mikeodriscoll_resume.pdf

  publish-github-pages:
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: generate-resume
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Resume Release
          path: release
      - name: Debug list
        run: ls -R
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: release/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
